spring:
  application:
    name: challenge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema:
#        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true